In [272]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [273]:
productivity = '~/uniwork/ads/ADS-European-Productivity/Datasets/cleaned_Productivity.csv'
prod_df = pd.read_csv(productivity)
prod_df.drop(['2000', '2001','2002','2003','2004'], axis = 1, inplace =True)

In [274]:
prod_df.drop('mean', axis = 1, inplace = True)
prod_df

LOCATION       2005        2006        2007       2008       2009  \
0       AUS  47.099677   47.342066   47.873036  49.523676  49.111719   
1       AUT  60.632340   62.218785   63.814049  63.814456  63.363388   
2       BEL  67.287921   67.637137   68.887444  68.464336  68.020751   
3       BGR  17.965425   18.618248   19.229785  19.475667  19.717737   
4       CAN  47.187987   47.742663   47.802103  47.658733  47.877704   
5       CHE  64.693828   66.315161   67.595243  68.253612  66.723475   
6       CHL  20.756781   21.576242   22.452244  22.983801  23.127019   
7       COL  10.232035   10.890402   11.347122  11.360227  11.063533   
8       CRI  13.718511   14.259665   14.453706  14.909054  15.331663   
9       CZE  32.765277   34.781571   36.256014  36.139167  35.303035   
10      DEU  59.900695   60.858653   61.577685  61.593702  59.739676   
11      DNK  64.048343   64.892447   65.012119  64.044269  63.453957   
12      ESP  45.562108   45.828539   46.335067  46.454358  47.573943   
13      EST  28.372540   29.802344   32.051758  30.939920  31.588678   
14      FIN  56.779062   58.155532   60.024417  59.322583  56.695101   
15      FRA  61.487911   63.018745   62.723395  62.323215  61.685771   
16      GBR  55.156626   56.070347   56.864362  56.899648  55.528490   
17      GRC  38.332984   39.980723   41.017728  40.454932  39.403018   
18      HRV  30.903320   31.427151   31.956235  31.884464  29.803838   
19      HUN  31.711223   33.059351   33.880508  34.775614  33.729408   
20      IRL  62.593898   62.959165   63.998384  62.217740  65.205840   
21      ISL  51.613242   52.938942   56.118409  54.473883  57.958666   
22      ISR  35.423816   36.576262   36.977028  36.936883  36.527230   
23      ITA  52.990201   52.873541   52.833352  52.532095  51.485627   
24      JPN  42.497598   42.564981   42.875805  42.736764  42.149500   
25      KOR  25.066255   26.109854   27.762018  29.325932  30.340215   
26      LTU  27.812775   30.040743   32.197778  32.957143  31.543369   
27      LUX  99.957636  102.035068  104.743364  99.685834  99.484621   
28      LVA  23.911079   25.497929   27.534660  27.520156  28.253320   
29      MEX  18.773197   19.139057   19.361361  19.244617  18.100579   
30      NLD  64.097939   65.051296   65.632495  66.009294  64.520326   
31      NOR  82.750646   82.157474   80.742255  78.348249  78.455084   
32      NZL  36.908863   37.421156   38.859858  37.664881  39.646401   
33      POL  26.725170   27.469543   28.184305  28.402336  29.321396   
34      PRT  35.272311   35.927996   36.491637  36.727659  36.569423   
35      ROU  18.818376   20.350859   21.467073  23.850073  23.643342   
36      RUS  20.051286   21.373371   22.622358  23.700889  22.631987   
37      SVK  30.452693   32.274839   34.710747  35.458839  34.443631   
38      SVN  36.938074   39.128271   40.808356  40.752803  38.181149   
39      SWE  63.473288   65.301313   65.489276  64.336167  63.430047   
40      TUR  32.580282   34.111688   35.924232  35.805009  34.328244   
41      USA  61.772075   62.356937   63.232583  64.042431  66.089234   
42      ZAF  17.469945   18.189686   19.043363  18.446211  18.952649   

          2010       2011       2012        2013        2014       2015  \
0    49.886548  50.465688  51.671243   52.558753   52.780926  54.099648   
1    64.291488  64.947960  65.645538   66.080679   66.327394  67.267651   
2    69.053627  68.581978  68.923207   69.517696   70.513657  71.604653   
3    20.847786  21.781488  22.497211   22.460713   22.607390  23.296069   
4    48.405298  49.181535  49.335662   50.068609   51.425818  51.340885   
5    68.620315  68.227615  68.494780   69.759903   70.447419  69.982344   
6    22.047521  22.524161  23.647491   23.997201   24.412230  24.525405   
7    11.114892  11.496924  11.629282   12.052849   12.371221  12.488134   
8    17.122775  17.944786  17.694625   18.620355   19.093774  19.707747   
9    36.128328  36.734795  36.886973   37.004724   37.432375  39.390083   
10   61.1

In [275]:
esi = "~/uniwork/ads/ADS-European-Productivity/Datasets/ESI_Clean.csv"
esi_df = pd.read_csv(esi)
esi_df.columns=esi_df.iloc[0]
esi_df.drop(0, inplace=True) 
geo = esi_df['Month-Year']
esi_df = esi_df.drop('Month-Year', axis = 1)
esi_df = esi_df.astype(np.float64)

esi_df['geo'] = geo
esi_df['2005'] = esi_df.filter(regex='-05').mean(axis=1)
esi_df['2006'] = esi_df.filter(regex='-06').mean(axis=1)
esi_df['2007'] = esi_df.filter(regex='-07').mean(axis=1)
esi_df['2008'] = esi_df.filter(regex='-08').mean(axis=1)
esi_df['2009'] = esi_df.filter(regex='-09').mean(axis=1)
esi_df['2010'] = esi_df.filter(regex='-10').mean(axis=1)
esi_df['2011'] = esi_df.filter(regex='-11').mean(axis=1)
esi_df['2012'] = esi_df.filter(regex='-12').mean(axis=1)
esi_df['2013'] = esi_df.filter(regex='-13').mean(axis=1)
esi_df['2014'] = esi_df.filter(regex='-14').mean(axis=1)
esi_df['2015'] = esi_df.filter(regex='-15').mean(axis=1)
esi_df['2016'] = esi_df.filter(regex='-16').mean(axis=1)
esi_df['2017'] = esi_df.filter(regex='-17').mean(axis=1)
esi_df['2018'] = esi_df.filter(regex='-18').mean(axis=1)
esi_df['2019'] = esi_df.filter(regex='-19').mean(axis=1)
esi_df['2020'] = esi_df.filter(regex='-20').mean(axis=1)
esi_df['2021'] = esi_df.filter(regex='-21').mean(axis=1)

esi_df = esi_df[['geo','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021']]
esi_df.drop([1, 2],axis = 0, inplace=True)

In [276]:

for index, row in esi_df.iterrows():
    if row.geo == 'EL.ESI':
        row.geo = 'GR.ESI'
    if row.geo == 'UK.ESI':
        row.geo = 'GB.ESI'
    
    esi_df.at[index, 'geo'] = pycountry.countries.get(alpha_2 = row.geo[:-4]).alpha_3

In [277]:
esi_df

0   geo        2005        2006        2007        2008       2009  \
3   BEL  100.966667  111.616667  112.150000   95.008333  80.416667   
4   BGR  107.725000  111.033333  117.575000  114.716667  89.433333   
5   CZE  108.166667  113.358333  114.400000  102.775000  80.383333   
6   DNK  103.783333  113.016667  105.891667   88.466667  83.983333   
7   DEU   93.783333  103.975000  105.808333   92.833333  82.025000   
8   EST  111.216667  116.666667  108.391667   87.825000  75.525000   
9   GRC  102.241667  108.100000  110.291667  101.166667  87.241667   
10  ESP  104.841667  104.125000  103.350000   83.741667  79.866667   
11  FRA  101.966667  107.641667  110.800000   93.575000  81.416667   
12  CYP  101.708333  103.475000  109.350000  106.533333  91.458333   
13  LVA  110.641667  113.833333  111.991667   91.191667  69.916667   
14  LTU  108.166667  113.508333  114.341667   96.316667  69.858333   
15  LUX  102.200000  105.325000  109.458333   93.483333  85.958333   
16  HUN   96.600000   98.891667   94.808333   88.066667  79.616667   
17  MLT   93.941667   95.200000  106.783333  100.966667  86.758333   
18  NLD   98.416667  111.666667  114.591667   99.083333  80.283333   
19  AUT   97.791667  110.241667  110.925000   92.183333  79.966667   
20  POL  101.841667  109.675000  119.633333  111.483333  88.541667   
21  PRT   98.325000  101.908333  108.350000   99.733333  88.883333   
22  ROU  106.033333  109.175000  111.900000  105.691667  79.391667   
23  SVN  103.191667  111.450000  111.975000   98.500000  78.733333   
24  SVK  106.966667  114.266667  116.525000  100.858333  79.233333   
25  FIN  107.150000  111.800000  112.375000   94.541667  83.341667   
26  SWE  101.283333  107.858333  109.666667   90.883333  83.458333   

0         2010        2011        2012        2013        2014        2015  \
3   102.525000  101.850000   91.033333   94.850000  100.600000  100.675000   
4    89.883333   92.066667   91.883333   92.166667   95.741667  100.316667   
5    95.625000   94.516667   87.833333   89.633333   98.725000  103.016667   
6   108.341667  101.016667   92.725000   97.091667  100.566667  101.708333   
7   104.333333  107.500000   99.500000  101.625000  103.866667  105.191667   
8    98.083333  102.341667   99.041667   99.425000   98.433333   95.333333   
9    85.383333   83.458333   83.016667   92.641667  101.016667   91.141667   
10   89.575000   89.391667   85.858333   90.650000   99.858333  107.750000   
11   99.016667  100.066667   89.025000   88.133333   91.216667   96.566667   
12   94.983333   87.766667   81.533333   82.208333   93.525000   99.375000   
13   92.066667   98.650000  101.250000  101.908333  101.175000   99.025000   
14   91.016667   99.300000   95.041667   99.766667   98.316667   98.483333   
15   96.450000  100.816667   87.641667   86.616667   89.916667   93.375000   
16   96.858333   93.641667   89.058333   97.200000  108.641667  109.433333   
17  100.925000   95.358333   94.550000  100.258333  105.100000  107.475000   
18   99.191667   97.641667   89.350000   91.633333  100.150000  103.966667   
19  100.575000   99.650000   94.650000   96.058333   97.025000   97.641667   
20  101.600000   98.908333   93.525000   92.075000   98.550000   99.950000   
21   97.533333   88.000000   81.500000   88.725000  100.925000  105.491667   
22   83.466667   90.733333   92.875000   93.541667   97.958333  102.925000   
23   94.500000   93.750000   82.900000   87.791667   98.483333  105.191667   
24   98.066667   97.033333   93.466667   91.266667  100.333333  101.841667   
25  105.691667  102.075000   93.483333   91.508333   89.808333   91.716667   
26  108.300000  102.816667   93.500000   95.633333  100.833333  102.483333   

0         2016        2017        2018        2019       2020        2021  
3   102.900000  105.233333  105.533333   97.800000  86.033333  111.150000  
4   102.741667  106.591667  106.958333  102.550000  82.658333   96.183333  
5   105.358333  106.741667  107.808333  103.783333  84.958333   94.008

In [278]:
#the full dataset doesn't load cause it's too big so this is just general government expenditure as percentage og gdp
gov_exp = '~/uniwork/ads/ADS-European-Productivity/Datasets/gov_exp.csv'
exp_df = pd.read_csv(gov_exp)

In [279]:
exp_df

DATAFLOW        LAST UPDATE freq    unit sector cofog99  \
0      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
1      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
2      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
3      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
4      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
...                       ...                ...  ...     ...    ...     ...   
40795  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40796  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40797  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40798  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40799  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   

      na_item geo  TIME_PERIOD  OBS_VALUE OBS_FLAG  
0          TE  AT         2005        7.8      NaN  
1          TE  AT         2006        7.7      NaN  
2          TE  AT         2007        7.6      NaN  
3          TE  AT         2008        7.2      NaN  
4          TE  AT         2009        7.8      NaN  
...       ...  ..          ...        ...      ...  
40795      TE  SK         2017       39.5      NaN  
40796      TE  SK         2018       39.7      NaN  
40797      TE  SK         2019       40.5      NaN  
40798      TE  SK         2020       44.8      NaN  
40799      TE  SK         2021       46.3      NaN  

[40800 rows x 11 columns]

In [280]:
#droping observation fact as there are not that many predited vales and it saves space
exp_df.drop('OBS_FLAG', axis = 1, inplace = True)

In [281]:

sectors = set(exp_df['cofog99'])
countries = set(exp_df['geo'])


In [282]:
#drop irrelevant columns
exp_df.drop('DATAFLOW', axis = 1, inplace = True)
exp_df.drop('LAST UPDATE', axis = 1, inplace = True)
exp_df.drop('unit', axis = 1, inplace = True)
exp_df.drop('sector', axis = 1, inplace = True)

In [283]:
exp_df.drop('freq', axis = 1, inplace = True)
exp_df.drop('na_item', axis = 1, inplace = True)
exp_df.head()

cofog99 geo  TIME_PERIOD  OBS_VALUE
0    GF01  AT         2005        7.8
1    GF01  AT         2006        7.7
2    GF01  AT         2007        7.6
3    GF01  AT         2008        7.2
4    GF01  AT         2009        7.8

In [284]:
exp_df

cofog99 geo  TIME_PERIOD  OBS_VALUE
0        GF01  AT         2005        7.8
1        GF01  AT         2006        7.7
2        GF01  AT         2007        7.6
3        GF01  AT         2008        7.2
4        GF01  AT         2009        7.8
...       ...  ..          ...        ...
40795   TOTAL  SK         2017       39.5
40796   TOTAL  SK         2018       39.7
40797   TOTAL  SK         2019       40.5
40798   TOTAL  SK         2020       44.8
40799   TOTAL  SK         2021       46.3

[40800 rows x 4 columns]

In [285]:
exp_df = exp_df[exp_df['cofog99'] != 'TOTAL']
exp_df

cofog99 geo  TIME_PERIOD  OBS_VALUE
0        GF01  AT         2005        7.8
1        GF01  AT         2006        7.7
2        GF01  AT         2007        7.6
3        GF01  AT         2008        7.2
4        GF01  AT         2009        7.8
...       ...  ..          ...        ...
40285  GF1009  SK         2017        1.4
40286  GF1009  SK         2018        1.3
40287  GF1009  SK         2019        1.2
40288  GF1009  SK         2020        1.3
40289  GF1009  SK         2021        1.2

[40290 rows x 4 columns]

In [286]:
#atempting to get 80 different colours
from matplotlib.colors import hsv_to_rgb

hue_values = np.linspace(0, 1, 80)
ones = np.ones_like(hue_values)
# Convert the hue values to RGB colors using the hsv_to_rgb function

colors = hsv_to_rgb(np.column_stack([hue_values, ones, ones]))




In [287]:
# plot values o for each country
# for country in countries:
#     print(country)
#     fig = plt.figure(figsize=(12, 10))
#     to_plot_df = exp_df[exp_df['geo'] == country]
#     for i, (cofog99, group_df) in enumerate(to_plot_df.groupby('cofog99')):
#         plt.plot(group_df['TIME_PERIOD'], group_df['OBS_VALUE'], color=colors[i], label=cofog99)

#     plt.xlabel('Time Period')
#     plt.ylabel('OBS_VALUE')
#     plt.show()

In [288]:
import seaborn as sns
import matplotlib.pyplot as plt

In [289]:
german_prod = prod_df.iloc[10].values[1:]
german_esi = es_df.iloc[7].values[1:]
german_expenditure = exp_df.loc[exp_df['geo'] == 'DE', 'OBS_VALUE'].values
german_expenditure = np.split(german_expenditure, 79)


In [290]:
import pycountry


In [291]:
#prepare government expenditure dataset so it has teh same country codes as productivity
exp_df_prod = exp_df.copy()
for country in countries:
    
    if country == 'EL':
        exp_df_prod.replace(country, 'GRC', inplace =True)
    else: exp_df_prod.replace(country, pycountry.countries.get(alpha_2=country).alpha_3, inplace =True)

In [292]:
countries = set(exp_df_prod.geo)
countries
# exp_df_prod[exp_df_prod['geo'] =='SVN']

{'AUT',
 'BEL',
 'BGR',
 'CHE',
 'CYP',
 'CZE',
 'DEU',
 'DNK',
 'ESP',
 'EST',
 'FIN',
 'FRA',
 'GRC',
 'HRV',
 'HUN',
 'IRL',
 'ISL',
 'ITA',
 'LTU',
 'LUX',
 'LVA',
 'MLT',
 'NLD',
 'NOR',
 'POL',
 'PRT',
 'ROU',
 'SVK',
 'SVN',
 'SWE'}

In [293]:
exp_df_prod

cofog99  geo  TIME_PERIOD  OBS_VALUE
0        GF01  AUT         2005        7.8
1        GF01  AUT         2006        7.7
2        GF01  AUT         2007        7.6
3        GF01  AUT         2008        7.2
4        GF01  AUT         2009        7.8
...       ...  ...          ...        ...
40285  GF1009  SVK         2017        1.4
40286  GF1009  SVK         2018        1.3
40287  GF1009  SVK         2019        1.2
40288  GF1009  SVK         2020        1.3
40289  GF1009  SVK         2021        1.2

[40290 rows x 4 columns]

In [294]:
#get rid of teh countries in expenditure but not in productivity
for country in countries:
    if country not in set(prod_df.LOCATION) or country not in set(esi_df.geo):
        exp_df_prod = exp_df_prod[exp_df_prod.geo != country]

In [295]:
#get rid of countries in productivity but not in expenditure
countries = set(prod_df.LOCATION)
for country in countries:
    if country not in set(exp_df_prod.geo) or country not in set(esi_df.geo):
        prod_df = prod_df[prod_df.LOCATION != country]


In [296]:
countries = set(esi_df.geo)
for country in countries:
    if country not in set(prod_df.LOCATION) or country not in set(exp_df_prod.geo):
        esi_df = esi_df[esi_df.geo != country]

In [297]:
countries = set(prod_df.LOCATION)

prod_timeseries = pd.melt(prod_df, id_vars = ['LOCATION'], var_name = 'YEAR', value_name= 'PRODUCTIVITY').sort_values('LOCATION')
prod_timeseries

LOCATION  YEAR  PRODUCTIVITY
0        AUT  2005     60.632340
198      AUT  2014     66.327394
154      AUT  2012     65.645538
220      AUT  2015     67.267651
132      AUT  2011     64.947960
..       ...   ...           ...
65       SWE  2007     65.489276
307      SWE  2018     69.514519
43       SWE  2006     65.301313
241      SWE  2015     69.074511
373      SWE  2021     73.669232

[374 rows x 3 columns]

In [301]:
esi_timeseries = pd.melt(esi_df, id_vars = ['geo'], var_name = 'YEAR', value_name= 'ESI').sort_values('geo')

In [298]:
cofog99 = set(exp_df_prod.cofog99)
cofog99

{'GF01',
 'GF0101',
 'GF0102',
 'GF0103',
 'GF0104',
 'GF0105',
 'GF0106',
 'GF0107',
 'GF0108',
 'GF02',
 'GF0201',
 'GF0202',
 'GF0203',
 'GF0204',
 'GF0205',
 'GF03',
 'GF0301',
 'GF0302',
 'GF0303',
 'GF0304',
 'GF0305',
 'GF0306',
 'GF04',
 'GF0401',
 'GF0402',
 'GF0403',
 'GF0404',
 'GF0405',
 'GF0406',
 'GF0407',
 'GF0408',
 'GF0409',
 'GF05',
 'GF0501',
 'GF0502',
 'GF0503',
 'GF0504',
 'GF0505',
 'GF0506',
 'GF06',
 'GF0601',
 'GF0602',
 'GF0603',
 'GF0604',
 'GF0605',
 'GF0606',
 'GF07',
 'GF0701',
 'GF0702',
 'GF0703',
 'GF0704',
 'GF0705',
 'GF0706',
 'GF08',
 'GF0801',
 'GF0802',
 'GF0803',
 'GF0804',
 'GF0805',
 'GF0806',
 'GF09',
 'GF0901',
 'GF0902',
 'GF0903',
 'GF0904',
 'GF0905',
 'GF0906',
 'GF0907',
 'GF0908',
 'GF10',
 'GF1001',
 'GF1002',
 'GF1003',
 'GF1004',
 'GF1005',
 'GF1006',
 'GF1007',
 'GF1008',
 'GF1009'}

In [302]:
esi_timeseries.head

<bound method NDFrame.head of      geo  YEAR         ESI
366  AUT  2021  111.916667
124  AUT  2010  100.575000
278  AUT  2017  112.033333
14   AUT  2005   97.791667
168  AUT  2012   94.650000
..   ...   ...         ...
65   SWE  2007  109.666667
153  SWE  2011  102.816667
43   SWE  2006  107.858333
131  SWE  2010  108.300000
373  SWE  2021  115.025000

[374 rows x 3 columns]>

In [303]:
prod_timeseries.head

<bound method NDFrame.head of     LOCATION  YEAR  PRODUCTIVITY
0        AUT  2005     60.632340
198      AUT  2014     66.327394
154      AUT  2012     65.645538
220      AUT  2015     67.267651
132      AUT  2011     64.947960
..       ...   ...           ...
65       SWE  2007     65.489276
307      SWE  2018     69.514519
43       SWE  2006     65.301313
241      SWE  2015     69.074511
373      SWE  2021     73.669232

[374 rows x 3 columns]>

In [304]:
exp_df_prod.head

<bound method NDFrame.head of       cofog99  geo  TIME_PERIOD  OBS_VALUE
0        GF01  AUT         2005        7.8
1        GF01  AUT         2006        7.7
2        GF01  AUT         2007        7.6
3        GF01  AUT         2008        7.2
4        GF01  AUT         2009        7.8
...       ...  ...          ...        ...
40285  GF1009  SVK         2017        1.4
40286  GF1009  SVK         2018        1.3
40287  GF1009  SVK         2019        1.2
40288  GF1009  SVK         2020        1.3
40289  GF1009  SVK         2021        1.2

[29546 rows x 4 columns]>

In [321]:
for i in cofog99:
    data = exp_df_prod[exp_df_prod.cofog99 == i]
    data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
    data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
    print(i)
    print("Correlation with productivity:")
    print(data[['prod', 'OBS_VALUE']].corr())
    print("Correlation with ESI:")
    print(data[['esi', 'OBS_VALUE']].corr())


/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in

GF08
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.017703
OBS_VALUE  0.017703   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.058064
OBS_VALUE -0.058064   1.000000
GF0505
Correlation with productivity:
              prod  OBS_VALUE
prod       1.00000   -0.04053
OBS_VALUE -0.04053    1.00000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.05519
OBS_VALUE -0.05519    1.00000
GF0803
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.155771
OBS_VALUE  0.155771   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.007768
OBS_VALUE -0.007768   1.000000
GF10
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.365964
OBS_VALUE  0.365964   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000   0.021571
OBS_VALUE  0.021571   1.000000
GF0106
Correlation with pr

/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in

                esi  OBS_VALUE
esi        1.000000  -0.016535
OBS_VALUE -0.016535   1.000000
GF0706
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.063396
OBS_VALUE -0.063396   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.008278
OBS_VALUE -0.008278   1.000000
GF02
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000  -0.517313
OBS_VALUE -0.517313   1.000000
Correlation with ESI:
               esi  OBS_VALUE
esi        1.00000   -0.00416
OBS_VALUE -0.00416    1.00000
GF0407
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.084915
OBS_VALUE  0.084915   1.000000
Correlation with ESI:
                esi  OBS_VALUE
esi        1.000000  -0.089011
OBS_VALUE -0.089011   1.000000
GF0406
Correlation with productivity:
               prod  OBS_VALUE
prod       1.000000   0.018217
OBS_VALUE  0.018217   1.000000
Correlation with ESI:
                esi  

/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['prod'] = np.asarray(prod_timeseries.PRODUCTIVITY).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['esi'] = np.asarray(esi_timeseries.ESI).astype(np.float64)
/tmp/ipykernel_89625/2179130700.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in

In [299]:
#correlation between government expenditure and productivity in germany
german_prod = german_prod.astype('float64')
j = 0
for i in german_expenditure:
    # print(i.dtype)
    print(list(sectors)[j])
    j+=1
    print(np.corrcoef(i, german_prod))
    

GF08
[[ 1.         -0.65784641]
 [-0.65784641  1.        ]]
GF0505
[[1.         0.81059526]
 [0.81059526 1.        ]]
GF0803
[[1.         0.90814876]
 [0.90814876 1.        ]]
GF10
[[1.        0.8580432]
 [0.8580432 1.       ]]
GF0106
[[1.         0.80265179]
 [0.80265179 1.        ]]
GF0907
[[nan nan]
 [nan  1.]]
GF0205
[[1.         0.36991713]
 [0.36991713 1.        ]]
GF0104
[[ 1.         -0.97424613]
 [-0.97424613  1.        ]]
GF0302
[[nan nan]
 [nan  1.]]
GF1008
[[1.         0.59021609]
 [0.59021609 1.        ]]
GF0402
[[1.         0.49595211]
 [0.49595211 1.        ]]
GF0506
[[nan nan]
 [nan  1.]]
GF1007
[[1.         0.72513942]
 [0.72513942 1.        ]]
GF0107
[[nan nan]
 [nan  1.]]
GF0502
[[nan nan]
 [nan  1.]]
GF0605
[[1.         0.50415944]
 [0.50415944 1.        ]]
GF0802
[[1.         0.39979028]
 [0.39979028 1.        ]]
GF0403
[[1.         0.75697087]
 [0.75697087 1.        ]]
GF1003
[[nan nan]
 [nan  1.]]
GF0301
[[nan nan]
 [nan  1.]]
GF05
[[nan nan]
 [nan  1.]]
GF0404
[

/home/andreea/miniforge3/envs/uni/lib/python3.11/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/andreea/miniforge3/envs/uni/lib/python3.11/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


In [300]:
#correlation between esi and general government expenditure in germany
german_esi = german_esi.astype('float64')
j = 0
for i in german_expenditure:
    # print(i.dtype)
    print(list(sectors)[j])
    j+=1
    print(np.corrcoef(i, german_esi))
    

GF08
[[ 1.         -0.25684333]
 [-0.25684333  1.        ]]
GF0505
[[ 1.         -0.05015437]
 [-0.05015437  1.        ]]
GF0803
[[ 1.        -0.0060638]
 [-0.0060638  1.       ]]
GF10
[[ 1.         -0.06650896]
 [-0.06650896  1.        ]]
GF0106
[[ 1.         -0.11328192]
 [-0.11328192  1.        ]]
GF0907
[[nan nan]
 [nan  1.]]
GF0205
[[ 1.         -0.06600237]
 [-0.06600237  1.        ]]
GF0104
[[ 1.         -0.06815167]
 [-0.06815167  1.        ]]
GF0302
[[nan nan]
 [nan  1.]]
GF1008
[[1.         0.27357299]
 [0.27357299 1.        ]]
GF0402
[[1.         0.26041691]
 [0.26041691 1.        ]]
GF0506
[[nan nan]
 [nan  1.]]
GF1007
[[1.         0.09721454]
 [0.09721454 1.        ]]
GF0107
[[nan nan]
 [nan  1.]]
GF0502
[[nan nan]
 [nan  1.]]
GF0605
[[1.         0.18463417]
 [0.18463417 1.        ]]
GF0802
[[1.         0.15770107]
 [0.15770107 1.        ]]
GF0403
[[1.         0.04280491]
 [0.04280491 1.        ]]
GF1003
[[nan nan]
 [nan  1.]]
GF0301
[[nan nan]
 [nan  1.]]
GF05
[[nan nan]
