In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
productivity = '~/uniwork/ads/ADS-European-Productivity/Datasets/cleaned_Productivity.csv'
prod_df = pd.read_csv(productivity)
prod_df.drop(['2000', '2001','2002','2003','2004'], axis = 1, inplace =True)

In [37]:
prod_df.drop('mean', axis = 1, inplace = True)
prod_df

LOCATION       2005        2006        2007       2008       2009  \
0       AUS  47.099677   47.342066   47.873036  49.523676  49.111719   
1       AUT  60.632340   62.218785   63.814049  63.814456  63.363388   
2       BEL  67.287921   67.637137   68.887444  68.464336  68.020751   
3       BGR  17.965425   18.618248   19.229785  19.475667  19.717737   
4       CAN  47.187987   47.742663   47.802103  47.658733  47.877704   
5       CHE  64.693828   66.315161   67.595243  68.253612  66.723475   
6       CHL  20.756781   21.576242   22.452244  22.983801  23.127019   
7       COL  10.232035   10.890402   11.347122  11.360227  11.063533   
8       CRI  13.718511   14.259665   14.453706  14.909054  15.331663   
9       CZE  32.765277   34.781571   36.256014  36.139167  35.303035   
10      DEU  59.900695   60.858653   61.577685  61.593702  59.739676   
11      DNK  64.048343   64.892447   65.012119  64.044269  63.453957   
12      ESP  45.562108   45.828539   46.335067  46.454358  47.573943   
13      EST  28.372540   29.802344   32.051758  30.939920  31.588678   
14      FIN  56.779062   58.155532   60.024417  59.322583  56.695101   
15      FRA  61.487911   63.018745   62.723395  62.323215  61.685771   
16      GBR  55.156626   56.070347   56.864362  56.899648  55.528490   
17      GRC  38.332984   39.980723   41.017728  40.454932  39.403018   
18      HRV  30.903320   31.427151   31.956235  31.884464  29.803838   
19      HUN  31.711223   33.059351   33.880508  34.775614  33.729408   
20      IRL  62.593898   62.959165   63.998384  62.217740  65.205840   
21      ISL  51.613242   52.938942   56.118409  54.473883  57.958666   
22      ISR  35.423816   36.576262   36.977028  36.936883  36.527230   
23      ITA  52.990201   52.873541   52.833352  52.532095  51.485627   
24      JPN  42.497598   42.564981   42.875805  42.736764  42.149500   
25      KOR  25.066255   26.109854   27.762018  29.325932  30.340215   
26      LTU  27.812775   30.040743   32.197778  32.957143  31.543369   
27      LUX  99.957636  102.035068  104.743364  99.685834  99.484621   
28      LVA  23.911079   25.497929   27.534660  27.520156  28.253320   
29      MEX  18.773197   19.139057   19.361361  19.244617  18.100579   
30      NLD  64.097939   65.051296   65.632495  66.009294  64.520326   
31      NOR  82.750646   82.157474   80.742255  78.348249  78.455084   
32      NZL  36.908863   37.421156   38.859858  37.664881  39.646401   
33      POL  26.725170   27.469543   28.184305  28.402336  29.321396   
34      PRT  35.272311   35.927996   36.491637  36.727659  36.569423   
35      ROU  18.818376   20.350859   21.467073  23.850073  23.643342   
36      RUS  20.051286   21.373371   22.622358  23.700889  22.631987   
37      SVK  30.452693   32.274839   34.710747  35.458839  34.443631   
38      SVN  36.938074   39.128271   40.808356  40.752803  38.181149   
39      SWE  63.473288   65.301313   65.489276  64.336167  63.430047   
40      TUR  32.580282   34.111688   35.924232  35.805009  34.328244   
41      USA  61.772075   62.356937   63.232583  64.042431  66.089234   
42      ZAF  17.469945   18.189686   19.043363  18.446211  18.952649   

          2010       2011       2012        2013        2014       2015  \
0    49.886548  50.465688  51.671243   52.558753   52.780926  54.099648   
1    64.291488  64.947960  65.645538   66.080679   66.327394  67.267651   
2    69.053627  68.581978  68.923207   69.517696   70.513657  71.604653   
3    20.847786  21.781488  22.497211   22.460713   22.607390  23.296069   
4    48.405298  49.181535  49.335662   50.068609   51.425818  51.340885   
5    68.620315  68.227615  68.494780   69.759903   70.447419  69.982344   
6    22.047521  22.524161  23.647491   23.997201   24.412230  24.525405   
7    11.114892  11.496924  11.629282   12.052849   12.371221  12.488134   
8    17.122775  17.944786  17.694625   18.620355   19.093774  19.707747   
9    36.128328  36.734795  36.886973   37.004724   37.432375  39.390083   
10   61.1

In [38]:
es = '~/uniwork/ads/ADS-European-Productivity/Datasets/ESI_Clean.csv'
es_df = pd.read_csv(es)
es_df = es_df.set_axis(es_df.iloc[0], axis=1).drop(es_df.index[0])

es_df = es_df.loc[:, ~es_df.columns.str.contains('Jan')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Feb')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Mar')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Apr')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('May')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Jun')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Jul')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Aug')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Sep')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Oct')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('Nov')]
es_df = es_df.loc[:, ~es_df.columns.str.contains('22')]

es_df

0  Month-Year Dec-05 Dec-06 Dec-07 Dec-08 Dec-09 Dec-10 Dec-11 Dec-12 Dec-13  \
1      EU.ESI  103.3  112.0  106.2   71.9   92.2  102.8   91.0   86.6   97.4   
2      EA.ESI  103.1  111.8  105.2   70.9   92.2  102.8   91.1   86.6   97.4   
3      BE.ESI  107.5  116.7  106.1   68.1   93.9  109.5   90.3   88.9  102.6   
4      BG.ESI  108.9  118.5  114.8   93.8   88.9   96.9   88.0   92.6   93.1   
5      CZ.ESI  110.8  115.8  111.4   76.7   87.3   99.9   86.7   85.4   94.4   
6      DK.ESI  105.3  112.9  106.0   75.5  101.9  104.8   91.1   92.7  100.3   
7      DE.ESI   97.9  106.9  102.5   73.2   93.2  111.9  102.6   97.1  105.0   
8      EE.ESI  116.6  117.6   99.0   69.4   87.8  104.1   97.7   98.6   98.8   
9      EL.ESI  104.4  110.0  107.9   86.0   89.2   82.8   80.9   88.9   92.9   
10     ES.ESI  105.6  107.0   99.7   69.6   87.6   89.4   85.6   84.9   97.7   
11     FR.ESI  102.7  109.5  109.3   69.3   95.6  104.2   89.8   85.4   91.1   
12     CY.ESI  100.8  108.9  107.9   95.1   92.8   92.4   83.1   76.3   86.8   
13     LV.ESI  112.5  115.6  105.8   74.1   77.7   97.4   99.2  102.6  102.2   
14     LT.ESI  114.4  112.8  110.3   72.2   77.1   99.8   94.7   97.0   97.9   
15     LU.ESI  103.8  109.3  107.6   72.7   97.7   97.2   91.6   78.4   91.2   
16     HU.ESI  101.0   95.2   96.3   77.3   88.1   99.8   84.5   91.0  107.1   
17     MT.ESI   96.8   89.0  107.3   79.2   96.8   99.8   93.8   95.5  103.6   
18     NL.ESI  104.9  116.8  111.7   74.9   94.7  101.8   91.3   86.0   97.7   
19     AT.ESI   99.5  112.3  104.2   71.8   91.1  101.2   95.2   91.8   99.0   
20     PL.ESI  105.1  118.2  120.5   96.5   96.7  103.3   93.3   89.8   97.1   
21     PT.ESI   99.2  106.4  107.1   83.7   97.3   94.7   76.8   82.5   98.5   
22     RO.ESI  109.3  111.9  111.4   89.7   85.5   87.4   89.7   94.3   94.2   
23     SI.ESI  104.6  113.3  110.2   73.8   90.4   93.8   89.8   84.0   90.5   
24     SK.ESI  108.0  118.3  108.0   79.8   94.7  103.7   95.8   89.4   98.1   
25     FI.ESI  108.0  113.4  107.7   74.6   96.7  108.4   91.3   90.4   92.7   
26     SE.ESI  104.3  108.6  106.1   71.8   99.4  109.1   90.4   85.8   99.9   

0  Dec-14 Dec-15 Dec-16 Dec-17 Dec-18 Dec-19 Dec-20 Dec-21  
1    98.1  104.7  107.1  114.5  108.5  103.2   96.2  114.3  
2    97.7  104.6  106.8  114.8  108.1  102.9   96.7  114.7  
3    94.3  103.2  105.0  106.4  100.1   97.4   98.3  111.0  
4    95.3  102.1  105.5  106.0  104.0  104.9   82.1  100.6  
5   103.1  103.9  108.5  108.0  108.8  102.7   90.6   94.0  
6    93.8  102.8  101.8  112.6  103.8  102.3  101.1  112.0  
7   101.8  105.1  108.1  113.7  108.9  101.0   97.8  111.7  
8    97.9   96.6  102.0  106.1  101.8   95.6   96.9  107.5  
9    99.5   91.2   96.9  102.3  102.5  111.2   94.2  109.9  
10  102.9  111.3  106.9  111.8  104.7  103.6   94.4  108.1  
11   90.3   98.0  102.9  112.4   99.8  101.3   95.0  113.3  
12   96.1  100.5  106.6  111.0  113.7  108.2   88.6  108.7  
13   99.2   99.3  101.3  105.4  105.5  102.7   91.8  100.8  
14   95.8   98.0  106.0  107.0  110.9  108.8   99.1  110.2  
15   90.7   94.8  101.8  110.4  104.3  103.6  105.4  111.9  
16  110.0  110.3  109.7  118.2  118.7  108.0   91.4  108.0  
17  103.9  104.5  109.3  117.9  108.3   94.9   89.9   93.2  
18  101.8  104.0  106.4  110.8  107.2  101.5   98.0  105.9  
19   93.3  101.9  104.9  119.6  108.5  101.9   95.6  110.1  
20  100.0  100.1  103.4  108.4  109.4  104.4   86.2  105.4  
21  102.1  104.3  109.7  114.0  112.3  106.7   92.4  109.3  
22  101.7  103.2  104.3  104.8  102.4  105.8   90.8  103.2  
23  101.4  106.1  106.8  114.4  109.4  103.8   92.8  102.9  
24  101.3  100.4  106.3  105.0  100.6   99.4   92.1   93.3  
25   86.4   92.1  102.7  114.3  100.8   96.4   92.7  109.3  
26   99.8  104.7  109.5  109.3  106.5   95.6   99.0  118.9

In [5]:
#the full dataset doesn't load cause it's too big so this is just general government expenditure as percentage og gdp
gov_exp = '~/uniwork/ads/ADS-European-Productivity/Datasets/gov_exp.csv'
exp_df = pd.read_csv(gov_exp)

In [6]:
exp_df

DATAFLOW        LAST UPDATE freq    unit sector cofog99  \
0      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
1      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
2      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
3      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
4      ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13    GF01   
...                       ...                ...  ...     ...    ...     ...   
40795  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40796  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40797  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40798  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   
40799  ESTAT:GOV_10A_EXP(1.0)  22/02/23 11:00:00    A  PC_GDP    S13   TOTAL   

      na_item geo  TIME_PERIOD  OBS_VALUE OBS_FLAG  
0          TE  AT         2005        7.8      NaN  
1          TE  AT         2006        7.7      NaN  
2          TE  AT         2007        7.6      NaN  
3          TE  AT         2008        7.2      NaN  
4          TE  AT         2009        7.8      NaN  
...       ...  ..          ...        ...      ...  
40795      TE  SK         2017       39.5      NaN  
40796      TE  SK         2018       39.7      NaN  
40797      TE  SK         2019       40.5      NaN  
40798      TE  SK         2020       44.8      NaN  
40799      TE  SK         2021       46.3      NaN  

[40800 rows x 11 columns]

In [7]:
exp_df.drop('OBS_FLAG', axis = 1, inplace = True)

In [8]:
set(exp_df['sector'])

{'S13'}

In [137]:

sectors = set(exp_df['cofog99'])
countries = set(exp_df['geo'])
countries

{'AT',
 'BE',
 'BG',
 'CH',
 'CY',
 'CZ',
 'DE',
 'DK',
 'EE',
 'EL',
 'ES',
 'FI',
 'FR',
 'HR',
 'HU',
 'IE',
 'IS',
 'IT',
 'LT',
 'LU',
 'LV',
 'MT',
 'NL',
 'NO',
 'PL',
 'PT',
 'RO',
 'SE',
 'SI',
 'SK'}

In [54]:
#make a dictionary to map the names of the things measured to what they actually represent
len(sectors)

80

In [11]:
set(exp_df['na_item'])

{'TE'}

In [12]:
set(exp_df['DATAFLOW'])

{'ESTAT:GOV_10A_EXP(1.0)'}

In [13]:
exp_df.drop('DATAFLOW', axis = 1, inplace = True)
exp_df.drop('LAST UPDATE', axis = 1, inplace = True)
exp_df.drop('unit', axis = 1, inplace = True)
exp_df.drop('sector', axis = 1, inplace = True)

In [14]:
exp_df.drop('freq', axis = 1, inplace = True)
exp_df.drop('na_item', axis = 1, inplace = True)
exp_df.head()

cofog99 geo  TIME_PERIOD  OBS_VALUE
0    GF01  AT         2005        7.8
1    GF01  AT         2006        7.7
2    GF01  AT         2007        7.6
3    GF01  AT         2008        7.2
4    GF01  AT         2009        7.8

In [15]:
exp_df

cofog99 geo  TIME_PERIOD  OBS_VALUE
0        GF01  AT         2005        7.8
1        GF01  AT         2006        7.7
2        GF01  AT         2007        7.6
3        GF01  AT         2008        7.2
4        GF01  AT         2009        7.8
...       ...  ..          ...        ...
40795   TOTAL  SK         2017       39.5
40796   TOTAL  SK         2018       39.7
40797   TOTAL  SK         2019       40.5
40798   TOTAL  SK         2020       44.8
40799   TOTAL  SK         2021       46.3

[40800 rows x 4 columns]

In [16]:
exp_df = exp_df[exp_df['cofog99'] != 'TOTAL']
exp_df

cofog99 geo  TIME_PERIOD  OBS_VALUE
0        GF01  AT         2005        7.8
1        GF01  AT         2006        7.7
2        GF01  AT         2007        7.6
3        GF01  AT         2008        7.2
4        GF01  AT         2009        7.8
...       ...  ..          ...        ...
40285  GF1009  SK         2017        1.4
40286  GF1009  SK         2018        1.3
40287  GF1009  SK         2019        1.2
40288  GF1009  SK         2020        1.3
40289  GF1009  SK         2021        1.2

[40290 rows x 4 columns]

In [17]:
#atempting to get 80 different colours
from matplotlib.colors import hsv_to_rgb

hue_values = np.linspace(0, 1, 80)
#asked chatgpt how to do this
# Convert the hue values to RGB colors using the hsv_to_rgb function
colors = hsv_to_rgb(np.column_stack([hue_values, np.ones_like(hue_values), np.ones_like(hue_values)]))




In [18]:
#plot values o for each country
# for country in countries:
#     print(country)
#     fig = plt.figure(figsize=(12, 10))
#     df = exp_df[exp_df['geo'] == country]
#     for i, (cofog99, group_df) in enumerate(df.groupby('cofog99')):
#         plt.plot(group_df['TIME_PERIOD'], group_df['OBS_VALUE'], color=colors[i], label=cofog99)
#
#     plt.xlabel('Time Period')
#     plt.ylabel('OBS_VALUE')
#     plt.show()

In [19]:
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
german_prod = prod_df.iloc[10].values[1:]
german_esi = es_df.iloc[7].values[1:]
german_expenditure = exp_df.loc[exp_df['geo'] == 'DE', 'OBS_VALUE'].values
german_expenditure = np.split(german_expenditure, 79)
german_expenditure

[array([6.4, 6.2, 6.1, 6.6, 6.8, 6.8, 6.9, 6.7, 6.5, 6.3, 5.9, 5.8, 5.7,
        5.7, 5.8, 6.1, 6.2]),
 array([1.7, 1.6, 1.5, 1.8, 1.7, 1.7, 1.7, 1.7, 2. , 2. , 1.9, 1.8, 1.9,
        1.9, 2. , 2.1, 2.3]),
 array([0.2, 0.2, 0.2, 0.3, 0.3, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5, 0.5,
        0.5, 0.5, 0.6, 0.7]),
 array([0.8, 0.8, 0.8, 0.9, 1. , 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1,
        1.2, 1.3, 1.4, 1.4]),
 array([0.7, 0.7, 0.7, 0.8, 0.9, 0.9, 0.9, 0.9, 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1.1]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
        0.1, 0.1, 0.2, 0.1]),
 array([2.9, 2.8, 2.7, 2.7, 2.7, 2.6, 2.6, 2.4, 2. , 1.7, 1.5, 1.3, 1.1,
        1. , 0.9, 0.7, 0.6]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1. , 1. , 0.9, 0.9, 1. , 1. , 0.9, 1.1, 1.1, 1. , 1. , 1. , 1. ,
        1.1, 1.1, 1.1, 1.1]),
 array([0.9, 0.9, 0.

In [105]:
countries

{'AT',
 'BE',
 'BG',
 'CH',
 'CY',
 'CZ',
 'DE',
 'DK',
 'EE',
 'EL',
 'ES',
 'FI',
 'FR',
 'HR',
 'HU',
 'IE',
 'IS',
 'IT',
 'LT',
 'LU',
 'LV',
 'MT',
 'NL',
 'NO',
 'PL',
 'PT',
 'RO',
 'SE',
 'SI',
 'SK'}

In [99]:
import pycountry


In [138]:
#prepare government expenditure dataset so it has teh same country codes as productivity
exp_df_prod = exp_df.copy()
for country in countries:
    
    if country == 'EL':
        exp_df_prod.replace(country, 'GRC', inplace =True)
    else: exp_df_prod.replace(country, pycountry.countries.get(alpha_2=country).alpha_3, inplace =True)

In [134]:
countries = set(exp_df_prod['geo'])

# exp_df_prod[exp_df_prod['geo'] =='SVN']

In [141]:
#get rid of teh countries in expenditure but not in productivity
for country in countries:
    if country not in prod_df['LOCATION']:
        exp_df_prod = exp_df_prod[exp_df_prod['geo'] != country]

In [144]:
#get rid of countries in productivity but not in expenditure
countries = set(prod_df['LOCATION'])
for country in countries:
    if country not in exp_df_prod['geo']:
        prod_df = prod_df[prod_df['LOCATION'] != country]


In [95]:
#correlation between government expenditure and productivity in germany
german_prod = german_prod.astype('float64')
j = 0
for i in german_expenditure:
    # print(i.dtype)
    print(list(sectors)[j])
    j+=1
    print(np.corrcoef(i, german_prod))
    

GF0605
[[ 1.         -0.65784641]
 [-0.65784641  1.        ]]
GF0104
[[1.         0.81059526]
 [0.81059526 1.        ]]
GF0604
[[1.         0.90814876]
 [0.90814876 1.        ]]
GF0703
[[1.        0.8580432]
 [0.8580432 1.       ]]
GF0603
[[1.         0.80265179]
 [0.80265179 1.        ]]
GF0502
[[nan nan]
 [nan  1.]]
GF0305
[[1.         0.36991713]
 [0.36991713 1.        ]]
GF1007
[[ 1.         -0.97424613]
 [-0.97424613  1.        ]]
GF0405
[[nan nan]
 [nan  1.]]
GF0205
[[1.         0.59021609]
 [0.59021609 1.        ]]
GF0706
[[1.         0.49595211]
 [0.49595211 1.        ]]
GF1005
[[nan nan]
 [nan  1.]]
GF0705
[[1.         0.72513942]
 [0.72513942 1.        ]]
GF0805
[[nan nan]
 [nan  1.]]
GF0402
[[nan nan]
 [nan  1.]]
GF0404
[[1.         0.50415944]
 [0.50415944 1.        ]]
GF0903
[[1.         0.39979028]
 [0.39979028 1.        ]]
GF0801
[[1.         0.75697087]
 [0.75697087 1.        ]]
GF0108
[[nan nan]
 [nan  1.]]
GF0907
[[nan nan]
 [nan  1.]]
GF03
[[nan nan]
 [nan  1.]]
GF10

In [97]:
#correlation between esi and general government expenditure in germany
german_esi = german_esi.astype('float64')
j = 0
for i in german_expenditure:
    # print(i.dtype)
    print(list(sectors)[j])
    j+=1
    print(np.corrcoef(i, german_esi))
    

GF0605
[[ 1.         -0.25684333]
 [-0.25684333  1.        ]]
GF0104
[[ 1.         -0.05015437]
 [-0.05015437  1.        ]]
GF0604
[[ 1.        -0.0060638]
 [-0.0060638  1.       ]]
GF0703
[[ 1.         -0.06650896]
 [-0.06650896  1.        ]]
GF0603
[[ 1.         -0.11328192]
 [-0.11328192  1.        ]]
GF0502
[[nan nan]
 [nan  1.]]
GF0305
[[ 1.         -0.06600237]
 [-0.06600237  1.        ]]
GF1007
[[ 1.         -0.06815167]
 [-0.06815167  1.        ]]
GF0405
[[nan nan]
 [nan  1.]]
GF0205
[[1.         0.27357299]
 [0.27357299 1.        ]]
GF0706
[[1.         0.26041691]
 [0.26041691 1.        ]]
GF1005
[[nan nan]
 [nan  1.]]
GF0705
[[1.         0.09721454]
 [0.09721454 1.        ]]
GF0805
[[nan nan]
 [nan  1.]]
GF0402
[[nan nan]
 [nan  1.]]
GF0404
[[1.         0.18463417]
 [0.18463417 1.        ]]
GF0903
[[1.         0.15770107]
 [0.15770107 1.        ]]
GF0801
[[1.         0.04280491]
 [0.04280491 1.        ]]
GF0108
[[nan nan]
 [nan  1.]]
GF0907
[[nan nan]
 [nan  1.]]
GF03
[[nan n